# Generated by Django 3.2 on 2021-05-02 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknownDoctor', max_length=50)),
                ('profilePicture', models.ImageField(default='profiles/DoctorProfilePictures/dummy_profile.png', upload_to='profiles/DoctorProfilePictures')),
                ('numberOfReportsAssigned', models.PositiveIntegerField(default=0)),
                ('numberOfReportsCompleted', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'doctor',
                'verbose_name_plural': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the hospital', max_length=100)),
            ],
            options={
                'verbose_name': 'hospital',
                'verbose_name_plural': 'hospitals',
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknownNurse', max_length=50)),
                ('profilePicture', models.ImageField(default='profiles/DoctorProfilePictures/dummy_profile.png', upload_to='profiles/NurseProfilePictures')),
                ('numberOfReportsCreated', models.PositiveIntegerField(default=0)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurses', to='medical_app_backend.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'nurse',
                'verbose_name_plural': 'nurses',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reportImage', models.ImageField(upload_to='')),
                ('createdOn', models.DateTimeField(auto_now=True)),
                ('completedOn', models.DateTimeField()),
                ('message', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('completed', models.CharField(choices=[('done', 'DONE'), ('pending', 'PENDING')], max_length=8)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reports', to='medical_app_backend.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='medical_app_backend.hospital')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='medical_app_backend.nurse')),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='medical_app_backend.hospital'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
