# Generated by Django 3.2 on 2021-05-01 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical_app_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='numberOfReportsAssigned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='numberOfReportsCompleted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profilePicture',
            field=models.ImageField(default='profiles/DoctorProfilePictures/dummy_profile.png', upload_to='profiles/DoctorProfilePictures'),
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePicture', models.ImageField(default='profiles/DoctorProfilePictures/dummy_profile.png', upload_to='profiles/NurseProfilePictures')),
                ('numberOfReportsCreated', models.PositiveIntegerField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurses', to='medical_app_backend.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'nurse',
                'verbose_name_plural': 'nurses',
            },
        ),
    ]
