# Generated by Django 3.2 on 2021-05-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app_backend', '0002_auto_20210501_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='name',
            field=models.CharField(default='unknownNurse', max_length=50),
        ),
    ]
