# Generated by Django 3.2 on 2021-05-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app_backend', '0003_nurse_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='numberOfReportsCreated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
