# Generated by Django 3.2 on 2021-05-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app_backend', '0003_auto_20210503_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='completed',
            field=models.CharField(choices=[('done', 'DONE'), ('pending', 'PENDING')], default='pending', editable=False, max_length=8),
        ),
    ]
