# Generated by Django 3.2 on 2021-05-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app_backend', '0004_alter_report_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reportImage',
            field=models.ImageField(upload_to='profiles/ReportImages'),
        ),
    ]
