# Generated by Django 3.2 on 2021-05-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app_backend', '0005_alter_report_reportimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='patientName',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
