# Generated by Django 3.2 on 2021-05-02 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app_backend', '0005_doctor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reportImage', models.ImageField(upload_to='')),
                ('createdOn', models.DateTimeField(auto_now=True)),
                ('completedOn', models.DateTimeField()),
                ('message', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('completed', models.CharField(choices=[('done', 'DONE'), ('pending', 'PENDING')], max_length=7)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reports', to='medical_app_backend.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='medical_app_backend.hospital')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='medical_app_backend.nurse')),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
            },
        ),
    ]
